"""recoverable application removal (dismissed_at)

Revision ID: e4cbb4aadccd
Revises: 485296d24828
Create Date: 2026-08-10 20:02:35.681831

Adds ``applications.dismissed_at`` / ``dismissed_reason`` so removing an
application is a RECOVERABLE state change instead of a ``DELETE``.

Why
---

The "Re-sync" rebuild hard-deleted rows (and their ``emails``) whose company
was absent from a bounded, inbox-only Gmail scan. On 2026-08-10 that destroyed
two real applications whose confirmation mail had merely been archived — the
scan could not see them, and absence was treated as proof they were stale.
The reasoning bug is fixed in ``jobtracker/cloud/applications.py``; this
revision removes the remaining sharp edge, so that even a wrong removal is
undoable rather than final.

Design notes
------------

- Both columns are plain nullable adds — ``NULL`` means "live", which is
  exactly the state every existing row is already in, so the upgrade needs no
  backfill and cannot change what any user sees.
- No index. The board query gains a ``dismissed_at IS NULL`` predicate on top
  of an owner filter that is already index-assisted, and a partial index
  (``WHERE dismissed_at IS NULL``) would be Postgres-only — it would drift from
  the SQLModel metadata that ``alembic check`` compares against on SQLite.
- ``batch_alter_table`` is used for SQLite compatibility only. Its default
  ``recreate="auto"`` leaves Postgres on a plain ``ALTER TABLE ADD COLUMN``,
  so the RLS policies and FORCE flag on ``applications`` are untouched.
- The downgrade drops both columns, which discards the record of what was
  dismissed. Rows themselves survive a downgrade — but they come back VISIBLE,
  since with the columns gone nothing is hidden.
"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e4cbb4aadccd'
down_revision: Union[str, Sequence[str], None] = '485296d24828'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dismissed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('dismissed_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_column('dismissed_reason')
        batch_op.drop_column('dismissed_at')

    # ### end Alembic commands ###
