/**
 * Sample inbox — realistic job-search emails with REAL classifier verdicts.
 *
 * Every email below is synthetic (invented companies, no real person's mail is
 * ever read). But the verdict attached to each one is NOT invented: it is the
 * exact output of the shipped 3-layer classifier — the same quantized int8
 * ONNX pipeline that runs on the Hugging Face Space `yadava5/jobtracker-
 * classifier` and mirrors `backend/jobtracker/classifier`. The verdicts and
 * per-layer traces here were generated by running these eleven emails through
 * that pipeline offline (rules → e5 embedding similarity → SetFit head, gated
 * at 0.85). Nothing was hand-tuned; whatever the model returned is what ships.
 *
 * Why precomputed rather than live: the model is ~23 MB and Transformers.js
 * needs WASM eval + a CDN fetch, both of which the app's strict CSP forbids
 * (see `next.config.ts`). So layers 2–3 are precomputed here, while layer 1
 * (pure-regex rules) still runs LIVE in the browser via `rulesLayer.ts` — the
 * `/demo/inbox` view recomputes it on the spot to prove the trace is real.
 *
 * Distribution (the real cascade at work): 8 answered by rules, 1 by the
 * embedding layer, 2 held below the 0.85 gate for human review.
 *
 * Arrival dates are RELATIVE, for the reason `demoData.ts` and `reviewQueue.ts`
 * already are: they were absolute (`2026-07-15` down to `2026-07-08`) and so
 * aged a day per day against a clock that kept moving — by the time applied#80
 * was filed the freshest mail here was 28 days old. Each seed carries
 * `receivedDaysAgo`, resolved against one "now" per render, which preserves the
 * fixtures' SHAPE (the 0,0,1,1,2,3,4,4,5,6,7 spread is exactly the spacing the
 * original calendar days had) while the days themselves stay current.
 *
 * Re-anchoring cannot invalidate a verdict, which is the specific worry #80
 * raised: `classifyWithRules(subject, body)` takes no date, and neither did the
 * offline pipeline that produced the layer-2/3 traces. Nothing here is
 * classified BY its arrival day, so moving that day changes no category, no
 * confidence and no trace. The page's claim that these are the real
 * classifier's output stays true.
 *
 * A function rather than a resolved constant, the same rule the other two
 * fixture families follow: frozen at module load it would bake the process's
 * start day in. One caveat stated plainly, because it is not fixed here —
 * `/demo/inbox` is a STATIC route, so a module-level resolution would bake the
 * BUILD day. Nothing renders `receivedAt` today, so there is no hydration
 * mismatch to have; if it is ever displayed, that route needs
 * `dynamic = "force-dynamic"` the way `/demo` already does, and the comment at
 * the top of `app/demo/page.tsx` explains why nothing weaker works.
 */
import { todayISO } from "@/lib/dashboard/age";
import { daysBefore } from "@/lib/demo/demoData";

export type LayerId = "rules" | "embeddings" | "setfit";
export type LayerState = "answered" | "passed" | "skipped";
export type Method = "rules" | "embeddings" | "setfit";

/** One row of the decision trace — what a single layer did with the email. */
export interface TraceStep {
  layer: LayerId;
  state: LayerState;
  /** Human-readable summary, e.g. "interview @ 88% cosine". */
  note: string;
  /** The layer's confidence for its call, or null when it never ran. */
  confidence: number | null;
}

export interface SampleVerdict {
  /** Final category — a classifier class, or "needs_review" below the gate. */
  category: string;
  /** Final confidence in [0,1]. */
  confidence: number;
  /** Which layer rendered the final call. */
  method: Method;
  /** True when confidence < 0.85 (the auto-file gate). */
  needsReview: boolean;
  /** The email's full path through the three layers. */
  trace: TraceStep[];
}

export interface SampleEmail {
  id: string;
  senderName: string;
  senderEmail: string;
  subject: string;
  /** Full body — also fed to the live layer-1 recompute. */
  body: string;
  /** Calendar day the sample "arrived" — resolved from the seed against the
   *  render's "today". */
  receivedAt: string;
  verdict: SampleVerdict;
}

/** A fixture email before its date is resolved: an age, not a calendar day. */
type SampleEmailSeed = Omit<SampleEmail, "receivedAt"> & {
  /** Whole days before "today" this message arrived. */
  receivedDaysAgo: number;
};

/** The confidence gate: below this, nothing is auto-filed.
 *
 * RE-EXPORTED, not defined — the one definition is
 * `lib/classification/gate.ts`. It moved there in #495 so a product surface
 * can read the number without pulling this module's eleven fixture emails
 * into its bundle. Existing readers of `@/lib/demo/sampleInbox` are
 * unaffected; a new reader that wants ONLY the gate should import the
 * definition directly. */
export { GATE } from "@/lib/classification/gate";

const SAMPLE_SEEDS: SampleEmailSeed[] = [
  {
    id: "s01",
    senderName: "Cedar Labs Recruiting",
    senderEmail: "no-reply@greenhouse.io",
    subject: "We received your application",
    body: "Thank you for applying to the Software Engineer, Platform role at Cedar Labs. Your application has been received and our team is reviewing it. We will be in touch if there is a match.",
    receivedDaysAgo: 0,
    verdict: {
      category: "applied",
      confidence: 0.95,
      method: "rules",
      needsReview: false,
      trace: [
        { layer: "rules", state: "answered", note: "applied @ 95% — regex answered", confidence: 0.95 },
        { layer: "embeddings", state: "skipped", note: "never ran", confidence: null },
        { layer: "setfit", state: "skipped", note: "never ran", confidence: null },
      ],
    },
  },
  {
    id: "s08",
    senderName: "Summit Platform",
    senderEmail: "no-reply@myworkday.com",
    subject: "Action required: complete your application",
    body: "Your application for the Full-Stack Engineer role is incomplete. Please complete the additional steps and submit your application to be considered. Additional information is required before we can review your application.",
    receivedDaysAgo: 0,
    verdict: {
      category: "pending_application",
      confidence: 0.95,
      method: "rules",
      needsReview: false,
      trace: [
        { layer: "rules", state: "answered", note: "pending_application @ 95% — regex answered", confidence: 0.95 },
        { layer: "embeddings", state: "skipped", note: "never ran", confidence: null },
        { layer: "setfit", state: "skipped", note: "never ran", confidence: null },
      ],
    },
  },
  {
    id: "s03",
    senderName: "Harbor Analytics Talent",
    senderEmail: "talent@harboranalytics.com",
    subject: "Next step: online assessment (90 minutes)",
    body: "As the next step in your application, please complete the HackerRank coding assessment linked below within 5 days. It should take about 90 minutes and covers data structures and SQL.",
    receivedDaysAgo: 1,
    verdict: {
      category: "assessment",
      confidence: 0.95,
      method: "rules",
      needsReview: false,
      trace: [
        { layer: "rules", state: "answered", note: "assessment @ 95% — regex answered", confidence: 0.95 },
        { layer: "embeddings", state: "skipped", note: "never ran", confidence: null },
        { layer: "setfit", state: "skipped", note: "never ran", confidence: null },
      ],
    },
  },
  {
    id: "s04",
    senderName: "Juniper Cloud Recruiting",
    senderEmail: "recruiting@junipercloud.io",
    subject: "Let's schedule your technical interview",
    body: "We enjoyed reviewing your application and would like to schedule a 45-minute technical interview next week. Please use the Calendly link to book a time that works for you to meet the hiring team.",
    receivedDaysAgo: 1,
    verdict: {
      category: "interview",
      confidence: 0.95,
      method: "rules",
      needsReview: false,
      trace: [
        { layer: "rules", state: "answered", note: "interview @ 95% — regex answered", confidence: 0.95 },
        { layer: "embeddings", state: "skipped", note: "never ran", confidence: null },
        { layer: "setfit", state: "skipped", note: "never ran", confidence: null },
      ],
    },
  },
  {
    id: "p9",
    senderName: "Meridian Robotics",
    senderEmail: "coordinator@meridianrobotics.com",
    subject: "Your onsite loop",
    body: "Your onsite loop is being arranged. We will confirm the schedule and the panel shortly so you can plan your day.",
    receivedDaysAgo: 2,
    verdict: {
      category: "interview",
      confidence: 0.8772,
      method: "embeddings",
      needsReview: false,
      trace: [
        { layer: "rules", state: "passed", note: "top other @ 50% — not confident enough", confidence: 0.5 },
        { layer: "embeddings", state: "answered", note: "interview @ 88% cosine", confidence: 0.8772 },
        { layer: "setfit", state: "skipped", note: "never ran", confidence: null },
      ],
    },
  },
  {
    id: "s05",
    senderName: "Beacon Health People Team",
    senderEmail: "people@beaconhealth.io",
    subject: "Congratulations — offer details inside",
    body: "We are pleased to extend an offer for the ML Engineer position. The compensation package, base salary, and your start date are in the attached offer letter. Please confirm and sign to accept the offer.",
    receivedDaysAgo: 3,
    verdict: {
      category: "offer",
      confidence: 0.95,
      method: "rules",
      needsReview: false,
      trace: [
        { layer: "rules", state: "answered", note: "offer @ 95% — regex answered", confidence: 0.95 },
        { layer: "embeddings", state: "skipped", note: "never ran", confidence: null },
        { layer: "setfit", state: "skipped", note: "never ran", confidence: null },
      ],
    },
  },
  {
    id: "s06",
    senderName: "Atlas Freight Careers",
    senderEmail: "careers@atlasfreight.com",
    subject: "Update on your application to Atlas Freight",
    body: "Thank you for your interest in the Software Engineer II role. After careful consideration we have decided to move forward with other candidates at this time. We appreciate the time you invested and wish you the best in your job search.",
    receivedDaysAgo: 4,
    verdict: {
      category: "rejection",
      confidence: 0.95,
      method: "rules",
      needsReview: false,
      trace: [
        { layer: "rules", state: "answered", note: "rejection @ 95% — regex answered", confidence: 0.95 },
        { layer: "embeddings", state: "skipped", note: "never ran", confidence: null },
        { layer: "setfit", state: "skipped", note: "never ran", confidence: null },
      ],
    },
  },
  {
    id: "s07",
    senderName: "Sam Patel",
    senderEmail: "sam@cedarlabs.com",
    subject: "Following up on your application status",
    body: "Hi Ayush, I wanted to follow up on your application for the Platform Engineer role and let you know it is still under review with the hiring committee. I will reach out with an update on your candidacy by the end of the week.",
    receivedDaysAgo: 4,
    verdict: {
      category: "follow_up",
      confidence: 0.95,
      method: "rules",
      needsReview: false,
      trace: [
        { layer: "rules", state: "answered", note: "follow_up @ 95% — regex answered", confidence: 0.95 },
        { layer: "embeddings", state: "skipped", note: "never ran", confidence: null },
        { layer: "setfit", state: "skipped", note: "never ran", confidence: null },
      ],
    },
  },
  {
    id: "s11",
    senderName: "Quarry Data Recruiting",
    senderEmail: "no-reply@lever.co",
    subject: "Thanks for applying to Quarry Data",
    body: "Thanks for applying to the Data Engineer position at Quarry Data. We have received your application and it is now in review. You will hear from us about next steps soon.",
    receivedDaysAgo: 5,
    verdict: {
      category: "applied",
      confidence: 0.9,
      method: "rules",
      needsReview: false,
      trace: [
        { layer: "rules", state: "answered", note: "applied @ 90% — regex answered", confidence: 0.9 },
        { layer: "embeddings", state: "skipped", note: "never ran", confidence: null },
        { layer: "setfit", state: "skipped", note: "never ran", confidence: null },
      ],
    },
  },
  {
    id: "s02",
    senderName: "Dana Ruiz",
    senderEmail: "dana@northstar.dev",
    subject: "Interested in chatting about a Backend Engineer role?",
    body: "Hi Ayush, I came across your background and think you could be a strong fit for a Backend Engineer opening on our team. Would you be open to a quick call to learn more about your experience?",
    receivedDaysAgo: 6,
    verdict: {
      category: "needs_review",
      confidence: 0.1922,
      method: "setfit",
      needsReview: true,
      trace: [
        { layer: "rules", state: "passed", note: "top interview @ 60% — not confident enough", confidence: 0.6 },
        { layer: "embeddings", state: "passed", note: "best interview @ 69% — below 0.85", confidence: 0.6866 },
        { layer: "setfit", state: "answered", note: "interview @ 19% softmax — below 0.70", confidence: 0.1922 },
      ],
    },
  },
  {
    id: "s09",
    senderName: "Maya Chen",
    senderEmail: "maya@earlystage.xyz",
    subject: "Quick question about your background",
    body: "Hi Ayush, I had a quick question about your background and some of the projects you have worked on recently. Do you have a few minutes this week?",
    receivedDaysAgo: 7,
    verdict: {
      category: "needs_review",
      confidence: 0.1947,
      method: "setfit",
      needsReview: true,
      trace: [
        { layer: "rules", state: "passed", note: "top other @ 50% — not confident enough", confidence: 0.5 },
        { layer: "embeddings", state: "passed", note: "best follow_up @ 81% — below 0.85", confidence: 0.8065 },
        { layer: "setfit", state: "answered", note: "follow_up @ 19% softmax — below 0.70", confidence: 0.1947 },
      ],
    },
  },
];

/** The sample inbox's eleven emails, dated against one `today`. */
export function sampleEmails(today: string = todayISO()): SampleEmail[] {
  return SAMPLE_SEEDS.map(({ receivedDaysAgo, ...email }) => ({
    ...email,
    receivedAt: daysBefore(today, receivedDaysAgo),
  }));
}

export interface SampleInboxStats {
  scanned: number;
  autoClassified: number;
  heldForReview: number;
  autoPct: number;
}

/**
 * Stats derived from the verdicts above — computed, never hardcoded.
 *
 * Defaults to the SEEDS rather than to `sampleEmails()`: every number here
 * counts verdicts, and no verdict depends on a date, so resolving eleven
 * calendar days to throw them away would be work in service of nothing.
 */
export function sampleInboxStats(
  emails: Pick<SampleEmail, "verdict">[] = SAMPLE_SEEDS,
): SampleInboxStats {
  const scanned = emails.length;
  const heldForReview = emails.filter((e) => e.verdict.needsReview).length;
  const autoClassified = scanned - heldForReview;
  const autoPct = scanned === 0 ? 0 : Math.round((autoClassified / scanned) * 100);
  return { scanned, autoClassified, heldForReview, autoPct };
}
