/**
 * Sample inbox — realistic job-search emails with REAL classifier verdicts.
 *
 * Every email below is synthetic (invented companies, no real person's mail is
 * ever read). But the verdict attached to each one is NOT invented: it is the
 * exact output of the shipped 3-layer classifier — the same quantized int8
 * ONNX pipeline that runs on the Hugging Face Space `yadava5/jobtracker-
 * classifier` and mirrors `backend/jobtracker/classifier`. The verdicts and
 * per-layer traces here were generated by running these eleven emails through
 * that pipeline offline (rules → e5 embedding similarity → SetFit head, gated
 * at 0.85). Nothing was hand-tuned; whatever the model returned is what ships.
 *
 * Why precomputed rather than live: the model is ~23 MB and Transformers.js
 * needs WASM eval + a CDN fetch, both of which the app's strict CSP forbids
 * (see `next.config.ts`). So layers 2–3 are precomputed here, while layer 1
 * (pure-regex rules) still runs LIVE in the browser via `rulesLayer.ts` — the
 * `/demo/inbox` view recomputes it on the spot to prove the trace is real.
 *
 * Distribution (the real cascade at work): 8 answered by rules, 1 by the
 * embedding layer, 2 held below the 0.85 gate for human review.
 */

export type LayerId = "rules" | "embeddings" | "setfit";
export type LayerState = "answered" | "passed" | "skipped";
export type Method = "rules" | "embeddings" | "setfit";

/** One row of the decision trace — what a single layer did with the email. */
export interface TraceStep {
  layer: LayerId;
  state: LayerState;
  /** Human-readable summary, e.g. "interview @ 88% cosine". */
  note: string;
  /** The layer's confidence for its call, or null when it never ran. */
  confidence: number | null;
}

export interface SampleVerdict {
  /** Final category — a classifier class, or "needs_review" below the gate. */
  category: string;
  /** Final confidence in [0,1]. */
  confidence: number;
  /** Which layer rendered the final call. */
  method: Method;
  /** True when confidence < 0.85 (the auto-file gate). */
  needsReview: boolean;
  /** The email's full path through the three layers. */
  trace: TraceStep[];
}

export interface SampleEmail {
  id: string;
  senderName: string;
  senderEmail: string;
  subject: string;
  /** Full body — also fed to the live layer-1 recompute. */
  body: string;
  /** ISO date the sample "arrived". */
  receivedAt: string;
  verdict: SampleVerdict;
}

/** The confidence gate: below this, nothing is auto-filed. */
export const GATE = 0.85;

export const SAMPLE_EMAILS: SampleEmail[] = [
  {
    id: "s01",
    senderName: "Cedar Labs Recruiting",
    senderEmail: "no-reply@greenhouse.io",
    subject: "We received your application",
    body: "Thank you for applying to the Software Engineer, Platform role at Cedar Labs. Your application has been received and our team is reviewing it. We will be in touch if there is a match.",
    receivedAt: "2026-07-15",
    verdict: {
      category: "applied",
      confidence: 0.95,
      method: "rules",
      needsReview: false,
      trace: [
        { layer: "rules", state: "answered", note: "applied @ 95% — regex answered", confidence: 0.95 },
        { layer: "embeddings", state: "skipped", note: "never ran", confidence: null },
        { layer: "setfit", state: "skipped", note: "never ran", confidence: null },
      ],
    },
  },
  {
    id: "s08",
    senderName: "Summit Platform",
    senderEmail: "no-reply@myworkday.com",
    subject: "Action required: complete your application",
    body: "Your application for the Full-Stack Engineer role is incomplete. Please complete the additional steps and submit your application to be considered. Additional information is required before we can review your application.",
    receivedAt: "2026-07-15",
    verdict: {
      category: "pending_application",
      confidence: 0.95,
      method: "rules",
      needsReview: false,
      trace: [
        { layer: "rules", state: "answered", note: "pending_application @ 95% — regex answered", confidence: 0.95 },
        { layer: "embeddings", state: "skipped", note: "never ran", confidence: null },
        { layer: "setfit", state: "skipped", note: "never ran", confidence: null },
      ],
    },
  },
  {
    id: "s03",
    senderName: "Harbor Analytics Talent",
    senderEmail: "talent@harboranalytics.com",
    subject: "Next step: online assessment (90 minutes)",
    body: "As the next step in your application, please complete the HackerRank coding assessment linked below within 5 days. It should take about 90 minutes and covers data structures and SQL.",
    receivedAt: "2026-07-14",
    verdict: {
      category: "assessment",
      confidence: 0.95,
      method: "rules",
      needsReview: false,
      trace: [
        { layer: "rules", state: "answered", note: "assessment @ 95% — regex answered", confidence: 0.95 },
        { layer: "embeddings", state: "skipped", note: "never ran", confidence: null },
        { layer: "setfit", state: "skipped", note: "never ran", confidence: null },
      ],
    },
  },
  {
    id: "s04",
    senderName: "Juniper Cloud Recruiting",
    senderEmail: "recruiting@junipercloud.io",
    subject: "Let's schedule your technical interview",
    body: "We enjoyed reviewing your application and would like to schedule a 45-minute technical interview next week. Please use the Calendly link to book a time that works for you to meet the hiring team.",
    receivedAt: "2026-07-14",
    verdict: {
      category: "interview",
      confidence: 0.95,
      method: "rules",
      needsReview: false,
      trace: [
        { layer: "rules", state: "answered", note: "interview @ 95% — regex answered", confidence: 0.95 },
        { layer: "embeddings", state: "skipped", note: "never ran", confidence: null },
        { layer: "setfit", state: "skipped", note: "never ran", confidence: null },
      ],
    },
  },
  {
    id: "p9",
    senderName: "Meridian Robotics",
    senderEmail: "coordinator@meridianrobotics.com",
    subject: "Your onsite loop",
    body: "Your onsite loop is being arranged. We will confirm the schedule and the panel shortly so you can plan your day.",
    receivedAt: "2026-07-13",
    verdict: {
      category: "interview",
      confidence: 0.8772,
      method: "embeddings",
      needsReview: false,
      trace: [
        { layer: "rules", state: "passed", note: "top other @ 50% — not confident enough", confidence: 0.5 },
        { layer: "embeddings", state: "answered", note: "interview @ 88% cosine", confidence: 0.8772 },
        { layer: "setfit", state: "skipped", note: "never ran", confidence: null },
      ],
    },
  },
  {
    id: "s05",
    senderName: "Beacon Health People Team",
    senderEmail: "people@beaconhealth.io",
    subject: "Congratulations — offer details inside",
    body: "We are pleased to extend an offer for the ML Engineer position. The compensation package, base salary, and your start date are in the attached offer letter. Please confirm and sign to accept the offer.",
    receivedAt: "2026-07-12",
    verdict: {
      category: "offer",
      confidence: 0.95,
      method: "rules",
      needsReview: false,
      trace: [
        { layer: "rules", state: "answered", note: "offer @ 95% — regex answered", confidence: 0.95 },
        { layer: "embeddings", state: "skipped", note: "never ran", confidence: null },
        { layer: "setfit", state: "skipped", note: "never ran", confidence: null },
      ],
    },
  },
  {
    id: "s06",
    senderName: "Atlas Freight Careers",
    senderEmail: "careers@atlasfreight.com",
    subject: "Update on your application to Atlas Freight",
    body: "Thank you for your interest in the Software Engineer II role. After careful consideration we have decided to move forward with other candidates at this time. We appreciate the time you invested and wish you the best in your job search.",
    receivedAt: "2026-07-11",
    verdict: {
      category: "rejection",
      confidence: 0.9,
      method: "rules",
      needsReview: false,
      trace: [
        { layer: "rules", state: "answered", note: "rejection @ 90% — regex answered", confidence: 0.9 },
        { layer: "embeddings", state: "skipped", note: "never ran", confidence: null },
        { layer: "setfit", state: "skipped", note: "never ran", confidence: null },
      ],
    },
  },
  {
    id: "s07",
    senderName: "Sam Patel",
    senderEmail: "sam@cedarlabs.com",
    subject: "Following up on your application status",
    body: "Hi Ayush, I wanted to follow up on your application for the Platform Engineer role and let you know it is still under review with the hiring committee. I will reach out with an update on your candidacy by the end of the week.",
    receivedAt: "2026-07-11",
    verdict: {
      category: "follow_up",
      confidence: 0.95,
      method: "rules",
      needsReview: false,
      trace: [
        { layer: "rules", state: "answered", note: "follow_up @ 95% — regex answered", confidence: 0.95 },
        { layer: "embeddings", state: "skipped", note: "never ran", confidence: null },
        { layer: "setfit", state: "skipped", note: "never ran", confidence: null },
      ],
    },
  },
  {
    id: "s11",
    senderName: "Quarry Data Recruiting",
    senderEmail: "no-reply@lever.co",
    subject: "Thanks for applying to Quarry Data",
    body: "Thanks for applying to the Data Engineer position at Quarry Data. We have received your application and it is now in review. You will hear from us about next steps soon.",
    receivedAt: "2026-07-10",
    verdict: {
      category: "applied",
      confidence: 0.9,
      method: "rules",
      needsReview: false,
      trace: [
        { layer: "rules", state: "answered", note: "applied @ 90% — regex answered", confidence: 0.9 },
        { layer: "embeddings", state: "skipped", note: "never ran", confidence: null },
        { layer: "setfit", state: "skipped", note: "never ran", confidence: null },
      ],
    },
  },
  {
    id: "s02",
    senderName: "Dana Ruiz",
    senderEmail: "dana@northstar.dev",
    subject: "Interested in chatting about a Backend Engineer role?",
    body: "Hi Ayush, I came across your background and think you could be a strong fit for a Backend Engineer opening on our team. Would you be open to a quick call to learn more about your experience?",
    receivedAt: "2026-07-09",
    verdict: {
      category: "needs_review",
      confidence: 0.1922,
      method: "setfit",
      needsReview: true,
      trace: [
        { layer: "rules", state: "passed", note: "top interview @ 60% — not confident enough", confidence: 0.6 },
        { layer: "embeddings", state: "passed", note: "best interview @ 69% — below 0.85", confidence: 0.6866 },
        { layer: "setfit", state: "answered", note: "interview @ 19% softmax — below 0.70", confidence: 0.1922 },
      ],
    },
  },
  {
    id: "s09",
    senderName: "Maya Chen",
    senderEmail: "maya@earlystage.xyz",
    subject: "Quick question about your background",
    body: "Hi Ayush, I had a quick question about your background and some of the projects you have worked on recently. Do you have a few minutes this week?",
    receivedAt: "2026-07-08",
    verdict: {
      category: "needs_review",
      confidence: 0.1947,
      method: "setfit",
      needsReview: true,
      trace: [
        { layer: "rules", state: "passed", note: "top other @ 50% — not confident enough", confidence: 0.5 },
        { layer: "embeddings", state: "passed", note: "best follow_up @ 81% — below 0.85", confidence: 0.8065 },
        { layer: "setfit", state: "answered", note: "follow_up @ 19% softmax — below 0.70", confidence: 0.1947 },
      ],
    },
  },
];

export interface SampleInboxStats {
  scanned: number;
  autoClassified: number;
  heldForReview: number;
  autoPct: number;
}

/** Stats derived from the verdicts above — computed, never hardcoded. */
export function sampleInboxStats(emails: SampleEmail[] = SAMPLE_EMAILS): SampleInboxStats {
  const scanned = emails.length;
  const heldForReview = emails.filter((e) => e.verdict.needsReview).length;
  const autoClassified = scanned - heldForReview;
  const autoPct = scanned === 0 ? 0 : Math.round((autoClassified / scanned) * 100);
  return { scanned, autoClassified, heldForReview, autoPct };
}
