/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check (cloud)
         * @description Return a minimal health response.
         *
         *     No database hit, no credential probe. Later issues will extend this to
         *     report Postgres connectivity (C2), Supabase auth (C3), and classifier
         *     availability (C6) once those subsystems are wired into the cloud app.
         */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Cloud API Root
         * @description Root endpoint with API information for the cloud deployment.
         */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Echo authenticated user
         * @description Return the authenticated Supabase user's UUID.
         *
         *     Useful for:
         *     - Web clients to confirm their JWT decodes correctly before
         *       mutating state.
         *     - Smoke probes after deploy: a 200 here proves both CORS and
         *       ``SUPABASE_JWT_SECRET`` are configured correctly on Vercel.
         */
        get: operations["auth_me_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/applications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Applications Cloud
         * @description List applications owned by the authenticated Supabase user, paginated.
         *
         *     The ``Depends(current_user)`` both enforces authentication (via the
         *     router-level dependency) and injects the resolved UUID so this
         *     handler can scope the query. Postgres RLS policies (see Alembic
         *     revision ``a8d4ec5fba26``) are a second line of defence: even if
         *     the ``WHERE user_id = ...`` clause were dropped, the DB would still
         *     return only rows matching ``auth.uid()``.
         *
         *     ``total`` is the full count of rows matching the (owner + filter)
         *     predicate — not the size of the returned page — so the UI can render an
         *     honest "X of Y" without a second request. Server-side ``LIMIT``/``OFFSET``
         *     keeps the transferred payload bounded regardless of account size; the
         *     default page size still fits a typical whole board in one response.
         *
         *     Dismissed rows are excluded by default: removal hides a row, it no longer
         *     deletes it. ``dismissed=true`` returns exactly those instead, which is the
         *     list an "undo" surface reads.
         */
        get: operations["list_applications_cloud_applications_get"];
        put?: never;
        /**
         * Create Application Cloud
         * @description Create an application scoped to the authenticated user.
         *
         *     The ``user_id`` column is set from the JWT's ``sub`` claim, not from
         *     any client-supplied value — there is no way for a client to write a
         *     row on behalf of another user through this endpoint. The Postgres
         *     RLS ``WITH CHECK`` clause would reject a mismatched insert as well,
         *     but checking here first avoids the round-trip on misconfigured
         *     clients.
         *
         *     ``applied_date`` and ``url`` are persisted when supplied. A malformed date
         *     is a visible 422: dropping it silently is exactly the bug that made the
         *     dialog's date and link disappear into ``notes``.
         */
        post: operations["create_application_cloud_applications_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/applications/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Application Summary Cloud
         * @description Return counts-only pipeline summary for the authenticated user.
         *
         *     Powers the dashboard stat tiles + funnel without transferring a single
         *     application row. Two aggregate queries run against the composite
         *     ``(user_id, status)`` index:
         *
         *     - ``GROUP BY status`` → per-status counts (≤7 rows regardless of how many
         *       applications the user has). ``total`` is their sum.
         *     - a windowed ``COUNT(*)`` for applications created in the last 7 days.
         *
         *     Both are O(1) in transfer and index-assisted in the DB, so this endpoint
         *     stays flat as an account scales from 10 to 10,000 applications — the whole
         *     reason it exists instead of counting client-side over the full list.
         */
        get: operations["application_summary_cloud_applications_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/applications/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Review Queue Cloud
         * @description The needs-classification queue: uncertain verdicts awaiting a decision.
         *
         *     These are the metadata-only Email rows the sync flagged ``needs_review``
         *     (unlinked, un-reviewed) — the real target of the dashboard's "N need
         *     classification" number, which is otherwise a dead count. Newest-first.
         *
         *     ONE ENTRY PER GMAIL THREAD. A conversation is one application, so being
         *     asked about it twice is being asked to do the same work twice: the owner's
         *     queue listed "Crusoe | Application Received" as two items (emails 58 and 73,
         *     thread ``19fed7e0706ee704``). The newest message of a thread represents it,
         *     and classifying it settles the rest (:func:`_settle_thread_siblings`).
         *     Collapsing happens here rather than in SQL so the fix also covers the
         *     duplicate rows earlier syncs already persisted; ``limit`` therefore bounds
         *     the rows READ, and the queue can return fewer entries than that.
         */
        get: operations["review_queue_cloud_applications_review_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/applications/review/{message_id}/classify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Classify Review Item Cloud
         * @description Classify a review item into a category — persists the decision + trains.
         *
         *     A lifecycle category with a nameable employer becomes a sticky, user-owned
         *     application; every choice records a training example (SetFit retrain path).
         *
         *     A 2xx does NOT on its own mean a row was filed: when the employer cannot be
         *     named the response carries ``needs_employer: true`` and the item stays in
         *     the queue. Callers must branch on that flag (and may re-POST with
         *     ``company``) rather than assuming success.
         *
         *     Accepts a correction for a message this database has never seen, provided
         *     the caller sends its metadata as ``message`` — the live scan's rows are
         *     verdicts about un-stored mail, and without this they were 404s. The message
         *     is stored under the JWT's user id and nowhere else, so the worst a bogus id
         *     can do is add a row to the caller's own mail listing.
         */
        post: operations["classify_review_item_cloud_applications_review__message_id__classify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/applications/statuses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Application Statuses Cloud
         * @description The canonical stage vocabulary — the one place a client should read it.
         *
         *     Declared ABOVE ``GET /{application_id}`` deliberately: FastAPI matches in
         *     declaration order and would otherwise try ``"statuses"`` as an int path
         *     param and answer 422. Same pattern as ``/summary`` and ``/review``.
         *
         *     Serves what :class:`ApplicationStatus` says, not a copy of it, so a client
         *     can assert its own ``<select>`` against this (or against the enum in
         *     ``/openapi.json``, which is generated from the same declaration) instead of
         *     hand-maintaining a fourth list that drifts.
         */
        get: operations["application_statuses_cloud_applications_statuses_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/applications/mail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Mail Listing Cloud
         * @description Every message this user has stored, whatever the classifier decided.
         *
         *     Declared ABOVE ``GET /{application_id}`` deliberately: FastAPI matches in
         *     declaration order and would otherwise try ``"mail"`` as an int path param
         *     and answer 422. Same pattern as ``/summary``, ``/review`` and ``/statuses``.
         *
         *     WHY THIS EXISTS
         *     ---------------
         *     ``/review`` is the only other listing of classified mail, and it filters to
         *     ``needs_review AND unlinked AND not-yet-reviewed``. That is the right set
         *     for a work queue and the wrong set for a correction surface, because those
         *     three predicates make a verdict unreachable the moment it is touched:
         *
         *     * a message already reviewed once drops out for good — emails 58 and 59 of
         *       the owner's account sit at ``needs_review`` with ``is_reviewed = true``
         *       and no endpoint in the product could name them, so no screen could
         *       change them;
         *     * a message linked to an application drops out too, so a ``rejection``
         *       filed as ``applied`` is a wrong stored verdict a user can see on the
         *       board and never correct at its source;
         *     * and for an account whose mail all classified confidently, ``/review``
         *       returns zero rows and the review UI never renders at all.
         *
         *     The write path never had that restriction — :func:`classify_review_item`
         *     selects on ``(user_id, message_id)`` alone — so correcting any of these
         *     already worked. What was missing was a way to *find* them. This is that
         *     read, and nothing more: no new write, no body, no state change.
         *
         *     SHAPE
         *     -----
         *     Newest first with an ``id`` tiebreak, for the same reason the applications
         *     listing has one: a sync writes a batch of rows carrying identical
         *     ``received_at`` values, tied rows are free to come back in a different
         *     order per request on Postgres, and paging a partial order drops some rows
         *     and repeats others.
         *
         *     One entry per MESSAGE — unlike ``/review``, which collapses a thread to its
         *     newest message because being asked the same question twice is duplicated
         *     work. Here the user is auditing what is stored, and every stored row is
         *     correctable individually, so hiding siblings would hide exactly the rows
         *     this endpoint exists to reach.
         */
        get: operations["mail_listing_cloud_applications_mail_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/applications/{application_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Application Detail Cloud
         * @description One application plus the underlying (metadata-only) mail — click-through.
         *
         *     Powers the detail view: subject / sender / date / snippet per message and a
         *     Gmail deep link to open the real conversation. Scoped to the owner (404 for
         *     anyone else's row).
         */
        get: operations["application_detail_cloud_applications__application_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Application Cloud
         * @description Hard-delete an application (and its linked emails). Scoped to the owner.
         */
        delete: operations["delete_application_cloud_applications__application_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Application Status Cloud
         * @description Apply a user's status correction — and make it sticky.
         *
         *     The new status is honoured verbatim (a human decision, not the advance-only
         *     guard) and future syncs will never overwrite it. It changes nothing about
         *     the linked mail: a stage is not a label for any individual message, and
         *     treating it as one poisoned the training corpus — see
         *     :func:`record_status_correction`. 404 when the row is not the caller's.
         */
        patch: operations["update_application_status_cloud_applications__application_id__patch"];
        trace?: never;
    };
    "/applications/{application_id}/split": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Split Application Cloud
         * @description Split a merged row into the applications its own mail describes.
         *
         *     The migration path for rows filed before an application was identified by
         *     employer AND role. It reads only what is already stored — every contributing
         *     message kept its subject and snippet — so it needs no Gmail call, no scan
         *     budget, and no rebuild. That matters: a rebuild is the only other route, it
         *     reads as destructive, and a bounded scan may not even reach the mail in
         *     question.
         *
         *     Conservative by construction:
         *
         *     - The row is retained for its EARLIEST cluster, so its id survives and every
         *       contact, interview and user correction stays attached to the application
         *       that has been on the board longest.
         *     - EVERY row's status is recomputed from its own mail rather than inherited —
         *       the siblings' and the retained row's alike. The row may already be
         *       terminal, and a terminal status is never left, so inheriting would give
         *       every sibling one requisition's rejection; leaving the retained row alone
         *       (which is what it used to do) leaves that same rejection on the one row
         *       whose remaining mail no longer contains it. The retained row is recomputed
         *       only when it is still sync-owned — a stage the user set survives a split.
         *     - Nothing is deleted and no mail is discarded: the messages are re-pointed,
         *       and anything that names no role stays with the retained row.
         *
         *     409 when there is nothing to split, which is the common case and not an
         *     error the caller should treat as a failure.
         */
        post: operations["split_application_cloud_applications__application_id__split_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/applications/{application_id}/deadline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Set Application Deadline Cloud
         * @description Set or clear when something is due on this application.
         *
         *     A date written here is the USER's, and is marked as such: later syncs will
         *     refresh a deadline that came from mail as newer mail supersedes it, and will
         *     never touch this one. Sending ``null`` clears both the date and its origin,
         *     because a source without a date is a claim about nothing.
         *
         *     404 when the row is not the caller's.
         */
        put: operations["set_application_deadline_cloud_applications__application_id__deadline_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/applications/{application_id}/dismiss": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Dismiss Application Cloud
         * @description 'Not an application / dismiss' — take the row off the board.
         *
         *     Reversible: the row leaves the board and the summary but is not deleted, so
         *     ``POST /applications/{id}/restore`` brings it back intact — mail, stored
         *     classifications and all, which is why the dismissal labels no message
         *     (see :func:`dismiss_application`).
         */
        post: operations["dismiss_application_cloud_applications__application_id__dismiss_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/applications/{application_id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Restore Application Cloud
         * @description Undo a removal — put a dismissed row back on the board, intact.
         *
         *     Works for both kinds of removal (a user dismiss and a re-sync's automatic
         *     one), because neither deletes anything. 404 when the row is not the
         *     caller's. Idempotent on a row that is already live.
         */
        post: operations["restore_application_cloud_applications__application_id__restore_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/gmail/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Gmail Status
         * @description Report whether Gmail is available, connected, and when it last synced.
         *
         *     Always 200 so the web UI can render an honest state (including "not yet
         *     configured by the operator") without treating it as an error.
         *
         *     Sync state is served from **here** rather than a second endpoint on purpose:
         *     the web already fetches this on the settings and inbox screens, "last synced
         *     3 minutes ago" belongs directly beside "connected as <address>", and the two
         *     are not independently meaningful — a cursor without a connection is nothing
         *     to render. One round trip, one user scope, one cache policy.
         */
        get: operations["gmail_status_auth_gmail_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/gmail/authorize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Gmail Authorize
         * @description Return the Google consent URL for the authenticated user.
         *
         *     The browser navigates to this URL (top-level) itself; we do not 302
         *     here so the user's JWT never has to accompany a cross-site redirect.
         *     ``access_type=offline`` + ``prompt=consent`` guarantee a refresh token.
         *
         *     The PKCE verifier minted here reaches the callback encrypted inside
         *     the signed ``state`` (see ``_sign_state``). Incremental scope merging
         *     (``include_granted_scopes``) is deliberately NOT requested: this app
         *     only ever wants ``gmail.readonly``, and merged prior grants would make
         *     the token response's scope set diverge from the requested one, which
         *     strict OAuth clients reject.
         */
        get: operations["gmail_authorize_auth_gmail_authorize_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/gmail/disconnect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Gmail Disconnect
         * @description Revoke the grant at Google, delete the stored token, drop the cursor.
         *
         *     The cursor is cleared FIRST and unconditionally — before the
         *     "was not connected" early return — because a ``historyId`` only means
         *     anything against the mailbox that issued it. A row surviving a disconnect
         *     would hand a re-linked (possibly different) account someone else's baseline,
         *     and an incremental sync from a foreign baseline skips mail.
         */
        post: operations["gmail_disconnect_auth_gmail_disconnect_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gmail/inbox": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Gmail Inbox
         * @description Read ONE server-side page of mail (filtered) and classify each message.
         *
         *     The honest end of the pipeline, now high-volume and filterable:
         *
         *     - ``range`` — ``3``/``6``/``9``/``12`` months, or all-time — becomes a
         *       Gmail ``newer_than:<N>m`` term.
         *     - ``scope`` — ``inbox`` (default) or ``anywhere`` (also searches archived /
         *       other-tab mail so filed-away interview & offer emails are found).
         *     - ``count`` — the client's total target; used only to clamp this page.
         *     - ``page_size`` / ``page_token`` — server-side pagination. The response
         *       carries ``next_page_token``; the web client loops until it reaches
         *       ``count`` or the token is null, showing a progress tally.
         *
         *     A single invocation fetches at most ``gmail_fetch_page_size`` messages
         *     (batched metadata gets, no bodies) so it stays inside the Vercel function
         *     budget; big mines are many bounded pages, not one fragile mega-call.
         *
         *     Bodies are never returned — only verdict metadata. The per-user, per-page
         *     short-TTL cache + ``ETag``/``If-None-Match`` are unchanged; auth is verified
         *     on every request before the cache is consulted.
         */
        get: operations["gmail_inbox_gmail_inbox_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gmail/pipeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Gmail Pipeline
         * @description Analyze an accumulated set of verdicts: category summary + follow-ups.
         *
         *     Pure aggregation over data the client already holds (no Gmail call, no
         *     bodies): the web client pages the mine via ``GET /gmail/inbox``, then posts
         *     the accumulated verdict metadata here to get the canonical whole-set
         *     category summary and the "No response — consider following up" flags across
         *     ALL pages (which no single page can compute alone).
         *
         *     Auth is enforced via the route dependency (the caller's own data; 401
         *     without a valid JWT), and the input is bounded by the fetch hard cap so it
         *     cannot be abused as an unbounded compute endpoint.
         */
        post: operations["gmail_pipeline_gmail_pipeline_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gmail/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Gmail Sync
         * @description Persist the classified job-search pipeline into Application rows.
         *
         *     This is what makes the dashboard show REAL data after connecting Gmail:
         *     the lifecycle mail (applied/interview/assessment/offer/rejection/…) is
         *     grouped into one application per company (furthest stage reached; rejection
         *     terminal) and idempotently upserted, scoped to the JWT's user.
         *
         *     Input source (see :class:`SyncRequest`): persist the client's already-mined
         *     ``items``, or — when omitted — fetch server-side and classify. The
         *     server-side fetch is INCREMENTAL whenever a Gmail ``historyId`` cursor is on
         *     file (``users.history.list`` from the stored baseline), and falls back to the
         *     bounded, STABLE full window otherwise: first sync, a fresh reconnect, an
         *     aged-out (404) cursor, an explicit range/count, or the "Re-sync" rebuild.
         *
         *     Every successful run records the caller's ``sync_state`` row —
         *     ``last_sync_at``, ``status`` and (server-fetch only) the mailbox baseline
         *     captured before the scan began. That row is what ``GET /auth/gmail/status``
         *     renders as "last synced …", and what stops the product from re-scanning a
         *     12-month window on every single visit.
         *
         *     Persistence is ``additive`` by default (durable upsert-only) and only
         *     ``rebuild`` on the explicit "Re-sync" button — which must be a server-side
         *     scan, so ``items`` + ``mode="rebuild"`` is a 400. Either way the upsert is
         *     idempotent (re-running never duplicates) and metadata-only (no bodies are
         *     stored), and the orphan reconciliation runs on BOTH paths — including an
         *     incremental run that found nothing, so a stranded classification can never
         *     become unreachable just because the sync got cheaper.
         */
        post: operations["gmail_sync_gmail_sync_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/account": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete the authenticated user's data
         * @description Purge every row owned by the authenticated user.
         *
         *     Idempotent — deleting an already-empty account still returns 200. The
         *     caller's Supabase *auth* user is removed separately by the web layer
         *     **after** this returns, so a failure here surfaces before the auth user is
         *     gone and the web flow can retry. (Google-side token revocation is a
         *     follow-up; deleting ``user_credentials`` here removes our stored copy.)
         */
        delete: operations["delete_account_account_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AccountDeletionResponse
         * @description Result of purging the caller's data.
         */
        AccountDeletionResponse: {
            /**
             * Deleted
             * @default true
             */
            deleted: boolean;
            /** Tables Cleared */
            tables_cleared: number;
        };
        /**
         * ApplicationDeadlineUpdate
         * @description Body for setting or clearing an application's deadline.
         *
         *     ``None`` clears it. There is deliberately no separate delete endpoint: set
         *     and clear are the same decision, and splitting them invites a UI that offers
         *     one without the other.
         */
        ApplicationDeadlineUpdate: {
            /** Due At */
            due_at?: string | null;
        };
        /**
         * ApplicationDetailResponse
         * @description An application plus the metadata-only mail it was derived from.
         */
        ApplicationDetailResponse: {
            application: components["schemas"]["CloudApplicationResponse"];
            /** Messages */
            messages: components["schemas"]["MessageRefResponse"][];
            /**
             * Split Candidates
             * @default []
             */
            split_candidates: components["schemas"]["SplitCandidateResponse"][];
        };
        /**
         * ApplicationStatus
         * @description Possible statuses for a job application.
         *
         *     THE canonical stage vocabulary. Everything that needs the list — the API
         *     body models, ``GET /applications/statuses``, the rollup's rank tables, the
         *     web's ``<select>`` — derives from here rather than restating it, because
         *     three hand-written copies is exactly how the board came to offer a stage
         *     (``assessment``) the API answers with a 422.
         *
         *     ``assessment`` is deliberately NOT a member: see :data:`CATEGORY_TO_STATUS`.
         * @enum {string}
         */
        ApplicationStatus: "applied" | "interviewing" | "offered" | "rejected" | "accepted" | "withdrawn" | "ghosted";
        /**
         * ApplicationStatusUpdate
         * @description Body for a user's status correction (PATCH /applications/{id}).
         */
        ApplicationStatusUpdate: {
            status: components["schemas"]["ApplicationStatus"];
        };
        /**
         * ApplicationSummaryResponse
         * @description Lightweight pipeline summary — counts only, no application rows.
         *
         *     This is the O(1)-transfer companion to the O(n) list endpoint. The
         *     dashboard's stat tiles + funnel need per-status counts, a total, and a
         *     "filed this week" number — none of which require shipping every row to
         *     the client. The backend computes them with two index-assisted aggregate
         *     queries (``GROUP BY status`` and a windowed ``COUNT``) against the
         *     ``ix_applications_user_id_status`` composite index, so response size and
         *     DB work stay constant as an account grows.
         *
         *     ``status_counts`` is keyed by the raw backend status value (``applied``,
         *     ``interviewing``, ``offered``, ``rejected``, ``accepted``, ``withdrawn``,
         *     ``ghosted``); only non-zero statuses are included. The frontend folds
         *     these into its display stages so stage semantics live in exactly one
         *     place (``lib/dashboard/summary.ts``).
         */
        ApplicationSummaryResponse: {
            /** Total */
            total: number;
            /** This Week */
            this_week: number;
            /** Status Counts */
            status_counts: {
                [key: string]: number;
            };
            /**
             * Needs Review
             * @default 0
             */
            needs_review: number;
        };
        /**
         * AuthMeResponse
         * @description Response shape for ``/auth/me``.
         */
        AuthMeResponse: {
            /** User Id */
            user_id: string;
            /**
             * Authenticated
             * @default true
             */
            authenticated: boolean;
        };
        /**
         * CloudApplicationCreate
         * @description Request body for the cloud POST /applications endpoint.
         *
         *     ``applied_date`` and ``url`` mirror the names :class:`CloudApplicationResponse`
         *     emits, so a hand-filed row round-trips through the same keys it came back
         *     under. Before they existed the dialog collected both and the API dropped
         *     both, and the web form worked around it by stringifying them into ``notes``.
         *
         *     ``applied_date`` is an ISO-8601 date — ``YYYY-MM-DD``, what the response
         *     returns. A full ISO datetime (``2026-08-10T14:03:00Z``, i.e. what
         *     ``Date.toISOString()`` produces) is accepted and truncated to its date;
         *     anything else is REJECTED with a 422 rather than silently dropped, which is
         *     the failure being fixed.
         */
        CloudApplicationCreate: {
            /** Company */
            company: string;
            /** Position */
            position: string;
            /** @default applied */
            status: components["schemas"]["ApplicationStatus"];
            /** Notes */
            notes?: string | null;
            /** Applied Date */
            applied_date?: string | null;
            /** Url */
            url?: string | null;
        };
        /**
         * CloudApplicationListResponse
         * @description Paginated list of applications owned by the authenticated user.
         */
        CloudApplicationListResponse: {
            /** Applications */
            applications: components["schemas"]["CloudApplicationResponse"][];
            /** Total */
            total: number;
        };
        /**
         * CloudApplicationResponse
         * @description Minimal response model — matches what downstream C11+ needs.
         */
        CloudApplicationResponse: {
            /** Id */
            id: number;
            /** User Id */
            user_id: string;
            /** Company */
            company: string;
            /** Position */
            position: string;
            status: components["schemas"]["ApplicationStatus"];
            /** Notes */
            notes?: string | null;
            /** Created At */
            created_at: string;
            /** Applied Date */
            applied_date?: string | null;
            /** Source */
            source?: string | null;
            /** Url */
            url?: string | null;
            /** Dismissed At */
            dismissed_at?: string | null;
            /** Dismissed Reason */
            dismissed_reason?: string | null;
            /** Due At */
            due_at?: string | null;
            /** Due Source */
            due_source?: string | null;
        };
        /**
         * EmailCategory
         * @description Classification categories for job-related emails.
         * @enum {string}
         */
        EmailCategory: "applied" | "pending_application" | "interview" | "rejection" | "offer" | "assessment" | "follow_up" | "needs_review" | "other";
        /** FollowUpOut */
        FollowUpOut: {
            /** Message Id */
            message_id: string;
            /** Company */
            company: string;
            /** Subject */
            subject: string;
            /** Days Since */
            days_since: number;
            /** Applied At */
            applied_at?: string | null;
        };
        /**
         * GmailAuthorizeResponse
         * @description The Google consent URL the browser should be sent to.
         */
        GmailAuthorizeResponse: {
            /** Authorization Url */
            authorization_url: string;
        };
        /** GmailDisconnectResponse */
        GmailDisconnectResponse: {
            /** Revoked */
            revoked: boolean;
            /** Message */
            message: string;
        };
        /**
         * GmailStatusResponse
         * @description Whether the deployment can offer Gmail, and whether this user linked it.
         *
         *     Also carries the caller's sync cursor state. The web app had nothing to
         *     render for "last synced …" — which is precisely why the product felt like it
         *     never synced and invited another manual re-sync on every visit. These fields
         *     are additive; ``configured=False`` short-circuits before any DB read, so an
         *     unconfigured deployment still answers without touching Postgres.
         *
         *     - ``last_sync_at`` — ISO-8601 of the last *successful* sync, never an
         *       attempt. ``null`` until one succeeds.
         *     - ``has_cursor`` — a Gmail ``historyId`` is stored, so the next sync can be
         *       incremental. ``false`` means the next sync is a full scan (first sync,
         *       post-disconnect, or an items-relay-only user).
         *     - ``sync_status`` / ``sync_error`` — the last recorded state
         *       (``idle``/``syncing``/``error``) and, on error, the failure's type name.
         */
        GmailStatusResponse: {
            /** Configured */
            configured: boolean;
            /** Connected */
            connected: boolean;
            /** Email */
            email?: string | null;
            /** Last Sync At */
            last_sync_at?: string | null;
            /**
             * Has Cursor
             * @default false
             */
            has_cursor: boolean;
            /** Sync Status */
            sync_status?: string | null;
            /** Sync Error */
            sync_error?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description Cloud health response. Intentionally minimal until C2/C3/C4 land.
         */
        HealthResponse: {
            /** Status */
            status: string;
            /** Version */
            version: string;
            /** Deployment */
            deployment: string;
            /** Environment */
            environment: string;
        };
        /** InboxResponse */
        InboxResponse: {
            /** Connected */
            connected: boolean;
            /** Scanned */
            scanned: number;
            /** Verdicts */
            verdicts: components["schemas"]["InboxVerdict"][];
            /** Note */
            note: string;
            /** Next Page Token */
            next_page_token?: string | null;
            /** Category Summary */
            category_summary: {
                [key: string]: number;
            };
            /** Query */
            query: string;
            /** Scope */
            scope: string;
            /** Range Months */
            range_months?: number | null;
            /**
             * Unreadable
             * @default 0
             */
            unreadable: number;
            /** Result Size Estimate */
            result_size_estimate?: number | null;
        };
        /**
         * InboxVerdict
         * @description One classifier verdict for one recent message. No body is included.
         */
        InboxVerdict: {
            /** Message Id */
            message_id: string;
            /** Subject */
            subject: string;
            /** Sender Email */
            sender_email: string;
            /** Sender Name */
            sender_name?: string | null;
            /** Category */
            category: string;
            /** Confidence */
            confidence: number;
            /** Method */
            method: string;
            /** Needs Review */
            needs_review: boolean;
            /** Received At */
            received_at?: string | null;
            /**
             * Company
             * @default
             */
            company: string;
        };
        /**
         * MailListResponse
         * @description A page of the user's stored mail, plus the counts the chips need.
         *
         *     ``total`` is the size of the CURRENT query — it respects both ``category``
         *     and ``q``, because it is the number ``page``/``page_size`` walk.
         *
         *     ``category_counts`` is deliberately different: it respects ``q`` but NOT
         *     ``category``, so each filter chip can show its own total while one of them
         *     is active. Counting only the filtered set would make every chip but the
         *     selected one read zero.
         */
        MailListResponse: {
            /** Messages */
            messages: components["schemas"]["MailMessageResponse"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Category Counts */
            category_counts: {
                [key: string]: number;
            };
        };
        /**
         * MailMessageResponse
         * @description One stored message in the full mail listing.
         *
         *     Deliberately METADATA ONLY. ``snippet`` is the persisted ``body_snippet``
         *     and there is no field for ``body_text`` or ``body_html``: the cloud sync
         *     never fetches a body and this listing is not the place to start.
         *
         *     ``category``/``confidence``/``method`` are the stored verdict verbatim —
         *     ``classified_as``, ``classification_confidence``, ``classification_method``
         *     — so a reader can see WHAT was decided and HOW, which is the difference
         *     between "the machine says applied" and "a rule matched at 0.71".
         *
         *     ``category`` carries the enum's own value (``"applied"``, ``"needs_review"``
         *     …), the same lowercase vocabulary ``?category=`` accepts and
         *     ``POST /review/{message_id}/classify`` takes back. One vocabulary end to
         *     end, so a value read here can be sent straight back as a correction.
         */
        MailMessageResponse: {
            /** Message Id */
            message_id: string;
            /** Thread Id */
            thread_id?: string | null;
            /** Subject */
            subject?: string | null;
            /** Sender Name */
            sender_name?: string | null;
            /** Sender Email */
            sender_email?: string | null;
            /** Received At */
            received_at?: string | null;
            /** Snippet */
            snippet?: string | null;
            /** Category */
            category?: string | null;
            /** Confidence */
            confidence?: number | null;
            /** Method */
            method?: string | null;
            /**
             * User Corrected
             * @default false
             */
            user_corrected: boolean;
            /**
             * Is Reviewed
             * @default false
             */
            is_reviewed: boolean;
            /** Application Id */
            application_id?: number | null;
            /** Company */
            company?: string | null;
            /** Gmail Link */
            gmail_link?: string | null;
        };
        /**
         * MessageRefResponse
         * @description One underlying email surfaced in the click-through detail view.
         */
        MessageRefResponse: {
            /** Message Id */
            message_id: string;
            /** Thread Id */
            thread_id?: string | null;
            /** Subject */
            subject?: string | null;
            /** Sender Name */
            sender_name?: string | null;
            /** Sender Email */
            sender_email?: string | null;
            /** Received At */
            received_at?: string | null;
            /** Snippet */
            snippet?: string | null;
            /** Category */
            category?: string | null;
            /** Confidence */
            confidence?: number | null;
            /** Gmail Link */
            gmail_link?: string | null;
        };
        /** PipelineAnalyzeRequest */
        PipelineAnalyzeRequest: {
            /** Items */
            items: components["schemas"]["PipelineItemIn"][];
            /** Stale Days */
            stale_days?: number | null;
        };
        /** PipelineAnalyzeResponse */
        PipelineAnalyzeResponse: {
            /** Total */
            total: number;
            /** Job Related */
            job_related: number;
            /** Category Summary */
            category_summary: {
                [key: string]: number;
            };
            /** Follow Ups */
            follow_ups: components["schemas"]["FollowUpOut"][];
        };
        /**
         * PipelineItemIn
         * @description One classified message the client asks the pipeline analytics about.
         *
         *     ``confidence`` (the classifier's confidence for ``category``) is what the
         *     sync now gates on: without it, a low-confidence guess used to manufacture a
         *     fake ``interviewing``/``offered`` row. ``thread_id``/``snippet`` let a
         *     persisted row deep-link + show the underlying mail in the detail view.
         */
        PipelineItemIn: {
            /** Message Id */
            message_id: string;
            /** Category */
            category: string;
            /**
             * Sender Email
             * @default
             */
            sender_email: string;
            /**
             * Subject
             * @default
             */
            subject: string;
            /** Sender Name */
            sender_name?: string | null;
            /** Received At */
            received_at?: string | null;
            /**
             * Confidence
             * @default 0
             */
            confidence: number;
            /** Thread Id */
            thread_id?: string | null;
            /**
             * Snippet
             * @default
             */
            snippet: string;
        };
        /**
         * RemovedApplicationOut
         * @description One row a rebuild took off the board, named so the UI can say which.
         */
        RemovedApplicationOut: {
            /** Id */
            id: number;
            /** Company */
            company: string;
        };
        /**
         * ReviewClassifyRequest
         * @description Body for classifying a review item into a category.
         *
         *     ``company`` is optional and only consulted when the pipeline cannot name the
         *     employer from the mail itself. That is the second half of the round trip the
         *     ``needs_employer`` response opens: the caller is told what is missing and
         *     re-sends the same classification with the company filled in.
         *
         *     ``application_id`` is the user answering "which of these is it about?". An
         *     employer can hold several applications, and a message that names no role —
         *     "Update on your application" — belongs to exactly one of them without saying
         *     which. The board asks; this carries the answer. Ignored when the id is not
         *     the caller's own row, or not at the employer the mail names.
         *
         *     ``message`` is what makes the same correction possible from the LIVE SCAN,
         *     whose rows may never have been stored (see :class:`ScannedMessageIn`).
         *     Consulted only when this message id is not already on file; a stored message
         *     is always corrected in place, so a client cannot use this to rewrite one.
         */
        ReviewClassifyRequest: {
            category: components["schemas"]["EmailCategory"];
            /** Company */
            company?: string | null;
            /** Application Id */
            application_id?: number | null;
            message?: components["schemas"]["ScannedMessageIn"] | null;
        };
        /**
         * ReviewItemResponse
         * @description One needs-classification queue entry (an uncertain verdict).
         */
        ReviewItemResponse: {
            /** Message Id */
            message_id: string;
            /** Thread Id */
            thread_id?: string | null;
            /** Subject */
            subject?: string | null;
            /** Sender Name */
            sender_name?: string | null;
            /** Sender Email */
            sender_email?: string | null;
            /** Received At */
            received_at?: string | null;
            /** Snippet */
            snippet?: string | null;
            /** Confidence */
            confidence?: number | null;
            /** Gmail Link */
            gmail_link?: string | null;
        };
        /**
         * ReviewQueueResponse
         * @description The needs-classification queue for the authenticated user.
         */
        ReviewQueueResponse: {
            /** Items */
            items: components["schemas"]["ReviewItemResponse"][];
            /** Total */
            total: number;
        };
        /**
         * ScannedMessageIn
         * @description The metadata needed to STORE a message the live scan has only mined.
         *
         *     The live-scan view (``/inbox?view=scan``) reads Gmail directly and holds
         *     nothing: its rows are verdicts about messages this database has never seen.
         *     Correcting one of them therefore has to persist the message first, or the
         *     correction lands on a row that does not exist — ``classify_review_item``
         *     answers 404 and the user's click does nothing.
         *
         *     Filing first is NOT a substitute. ``pipeline.collect_review_items`` keeps
         *     only ``needs_review`` mail and lifecycle mail at/above the 0.70 review
         *     floor, so the exact case this exists for — an assessment email the
         *     classifier called ``other`` at 0% — is dropped by ``POST /gmail/sync`` and
         *     can never be reached by a correction. The user can see the row; nothing in
         *     the product could store it.
         *
         *     ``received_at`` is REQUIRED and is never defaulted to "now": ``Email``
         *     requires a receive time and :func:`_persist_message_refs` deliberately skips
         *     undated messages rather than fabricating one. A client that has no date for
         *     a row must not offer the correction at all.
         *
         *     ``category``/``confidence``/``method`` are the classifier's verdict AS THE
         *     SCAN SHOWED IT. They are stored on the minted row so it starts out as a
         *     faithful copy of what the user was looking at — the same thing a sync would
         *     have written — and the correction is then applied on top of it, leaving the
         *     normal "was X, user says Y" trail instead of a row that claims the user's
         *     label was the machine's all along.
         */
        ScannedMessageIn: {
            /** Sender Email */
            sender_email: string;
            /**
             * Received At
             * Format: date-time
             */
            received_at: string;
            /** Subject */
            subject?: string | null;
            /** Sender Name */
            sender_name?: string | null;
            /** Thread Id */
            thread_id?: string | null;
            /** Snippet */
            snippet?: string | null;
            category?: components["schemas"]["EmailCategory"] | null;
            /** Confidence */
            confidence?: number | null;
            /** Method */
            method?: string | null;
        };
        /**
         * SplitCandidateResponse
         * @description One application hiding inside a row that was filed before identity existed.
         */
        SplitCandidateResponse: {
            /** Role */
            role?: string | null;
            /** Req Id */
            req_id?: string | null;
            /** Message Ids */
            message_ids: string[];
            /**
             * Retains Row
             * @default false
             */
            retains_row: boolean;
        };
        /**
         * StatusVocabularyResponse
         * @description The canonical stage vocabulary, served so no client has to restate it.
         *
         *     Every field is DERIVED from :class:`ApplicationStatus` /
         *     :data:`CATEGORY_TO_STATUS` at import time, so this endpoint and the 422 a
         *     bad ``PATCH`` earns cannot disagree. It exists because they did: the board
         *     offered ``assessment``, the file-by-hand dialog offered six of the seven,
         *     and the API accepted a different seven.
         *
         *     - ``statuses`` — the settable stages, in lifecycle order. THE list.
         *     - ``default`` — what a new row starts at.
         *     - ``category_to_status`` — how a classifier verdict maps onto a stage, for
         *       a client that wants to show ``assessment`` mail under ``interviewing``.
         *       A category absent from this map asserts no stage.
         *     - ``classifier_categories`` — everything the classifier can emit. A
         *       SUPERSET of the mapping's keys and NOT interchangeable with ``statuses``;
         *       confusing the two is the original defect.
         */
        StatusVocabularyResponse: {
            /** Statuses */
            statuses: string[];
            /** Default */
            default: string;
            /** Category To Status */
            category_to_status: {
                [key: string]: string;
            };
            /** Classifier Categories */
            classifier_categories: string[];
        };
        /**
         * SyncRequest
         * @description Sync the classified pipeline into the user's Application rows.
         *
         *     Input source — two ways to supply the scan: pass ``items`` to persist an
         *     already-mined set (the inbox workbench relays what it fetched), or omit them
         *     to have the server fetch a bounded, recent window itself and classify it
         *     (the dashboard's connect-time backfill). ``count``/``range``/``scope`` tune
         *     the server-fetch source.
         *
         *     Persistence ``mode`` — how the scan is merged:
         *
         *     - ``"additive"`` (DEFAULT): upsert-only. Insert newly-found applications and
         *       advance/refresh existing ones; NEVER delete a previously-found row just
         *       because this scan's window missed it. The durable path every routine/auto
         *       sync must use so the pipeline accumulates rather than vanishing run-to-run.
         *     - ``"rebuild"``: the destructive purge+rebuild — wipe the Gmail-derived board
         *       and rebuild it from this scan. Reserved for the EXPLICIT user "Re-sync"
         *       button (a deliberate "start clean"); manual/user-corrected rows are still
         *       preserved. **Server-fetch only**: ``mode="rebuild"`` together with
         *       ``items`` is REJECTED with 400, because a purge may only be computed from
         *       a scan the server made itself with ``scope="anywhere"``. Relayed items are
         *       additive-only.
         */
        SyncRequest: {
            /** Items */
            items?: components["schemas"]["PipelineItemIn"][] | null;
            /** Count */
            count?: number | null;
            /** Range */
            range?: string | null;
            /** Scope */
            scope?: string | null;
            /** Mode */
            mode?: string | null;
        };
        /** SyncResponse */
        SyncResponse: {
            /** Created */
            created: number;
            /** Updated */
            updated: number;
            /** Applications */
            applications: number;
            /** Scanned */
            scanned: number;
            /**
             * Unreadable
             * @default 0
             */
            unreadable: number;
            /**
             * Stopped By
             * @default complete
             */
            stopped_by: string;
            /** Result Size Estimate */
            result_size_estimate?: number | null;
            /**
             * Purged
             * @default 0
             */
            purged: number;
            /**
             * Needs Review
             * @default 0
             */
            needs_review: number;
            /**
             * Removed
             * @default []
             */
            removed: components["schemas"]["RemovedApplicationOut"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    auth_me_auth_me_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthMeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_applications_cloud_applications_get: {
        parameters: {
            query?: {
                /** @description 1-based page number. */
                page?: number;
                /** @description Rows per page (capped so a single response stays bounded). */
                page_size?: number;
                /** @description Filter to a single application status. */
                status?: components["schemas"]["ApplicationStatus"] | null;
                /** @description Case-insensitive substring match on company. */
                company?: string | null;
                /** @description Case-insensitive substring match on company/position/notes. */
                search?: string | null;
                /** @description Return the REMOVED rows instead of the live board — what a re-sync took off and what the user dismissed, so either can be restored. */
                dismissed?: boolean;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CloudApplicationListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_application_cloud_applications_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CloudApplicationCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CloudApplicationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    application_summary_cloud_applications_summary_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationSummaryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_queue_cloud_applications_review_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewQueueResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    classify_review_item_cloud_applications_review__message_id__classify_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                message_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewClassifyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    application_statuses_cloud_applications_statuses_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusVocabularyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mail_listing_cloud_applications_mail_get: {
        parameters: {
            query?: {
                /** @description 1-based page number. */
                page?: number;
                /** @description Rows per page (capped so a single response stays bounded). */
                page_size?: number;
                /** @description Filter to one stored verdict. Does not affect `category_counts`. */
                category?: components["schemas"]["EmailCategory"] | null;
                /** @description Case-insensitive substring match on subject/sender. */
                q?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MailListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    application_detail_cloud_applications__application_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                application_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_application_cloud_applications__application_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                application_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_application_status_cloud_applications__application_id__patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                application_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplicationStatusUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CloudApplicationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    split_application_cloud_applications__application_id__split_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                application_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CloudApplicationResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_application_deadline_cloud_applications__application_id__deadline_put: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                application_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplicationDeadlineUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CloudApplicationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dismiss_application_cloud_applications__application_id__dismiss_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                application_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    restore_application_cloud_applications__application_id__restore_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                application_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CloudApplicationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    gmail_status_auth_gmail_status_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GmailStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    gmail_authorize_auth_gmail_authorize_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GmailAuthorizeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    gmail_disconnect_auth_gmail_disconnect_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GmailDisconnectResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    gmail_inbox_gmail_inbox_get: {
        parameters: {
            query?: {
                count?: number | null;
                range?: string | null;
                scope?: string | null;
                page_size?: number | null;
                page_token?: string | null;
            };
            header?: {
                "if-none-match"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InboxResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    gmail_pipeline_gmail_pipeline_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PipelineAnalyzeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PipelineAnalyzeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    gmail_sync_gmail_sync_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SyncRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_account_account_delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountDeletionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
