/**
 * Step 2 of the footage pipeline: compose the captured frames into the shipped
 * clips with Remotion, and encode them small.
 *
 * Remotion is a devDependency and nothing it produces is imported by the app —
 * the shipped artifacts are video files under `public/footage/`. Its licence is
 * free for companies of three people or fewer; nothing here uses Remotion Lambda
 * or any hosted renderer.
 *
 * Both a modern codec and an H.264 fallback are encoded and MEASURED. Whether
 * two files ship or one is a decision made from those bytes, not from a
 * preference — see the README for the numbers this produced.
 */
import { bundle } from "@remotion/bundler";
import { renderMedia, renderStill, selectComposition } from "@remotion/renderer";
import { access, mkdir, readFile, stat, writeFile } from "node:fs/promises";
import path from "node:path";

import { CLIPS, HAND_CAPTURED, POSTER_AT } from "./clips.mjs";
import { SCENES } from "./scenes.mjs";

const WEB = process.cwd();
const FRAMES = process.env.FOOTAGE_FRAMES ?? path.join(WEB, ".footage-frames");
const OUT = path.join(WEB, "public", "footage");
const ONLY = process.env.FOOTAGE_ONLY?.split(",").map((s) => s.trim()).filter(Boolean);

const kb = (n) => `${(n / 1024).toFixed(1)} KB`;

// Driven by the scene list, never by whatever happens to be lying in the
// frames directory: an exploratory capture left behind there would otherwise be
// rendered and shipped as a clip nobody chose.
const scenes = SCENES.map((s) => s.id).filter((id) => !ONLY || ONLY.includes(id));
for (const id of scenes) {
  await access(path.join(FRAMES, id, "scene.json")).catch(() => {
    console.error(`No captured frames for "${id}" in ${FRAMES}. Run scripts/footage/capture.mjs first.`);
    process.exit(1);
  });
}

// The hand-captured clip renders only if its source recording is present. It is
// skipped LOUDLY rather than silently: an absent 11 MB .mov is the normal state
// of a fresh checkout, and a run that quietly shipped two clips where three were
// expected is how a page ends up with a hole in it.
// It must ALSO be in CLIPS — while it is held out (clips.mjs says why and what
// re-recording takes), encoding it would write files the manifest merge below
// immediately disowns.
const hasOauth = await access(path.join(FRAMES, HAND_CAPTURED.source)).then(() => true, () => false);
if (CLIPS.includes(HAND_CAPTURED.id) && (!ONLY || ONLY.includes(HAND_CAPTURED.id))) {
  if (hasOauth) scenes.unshift(HAND_CAPTURED.id);
  else
    console.warn(
      `  SKIPPING "${HAND_CAPTURED.id}": ${path.join(FRAMES, HAND_CAPTURED.source)} is not there.\n` +
        "  It is a hand-made screen recording of a real Google consent flow and cannot be\n" +
        "  regenerated by this pipeline. See scripts/footage/README.md.",
    );
}

console.log("bundling remotion…");
const serveUrl = await bundle({
  entryPoint: path.join(WEB, "scripts", "footage", "remotion", "index.ts"),
  // The captured frames ARE the static assets. Pointing Remotion's public dir
  // at them keeps ~600 intermediate PNGs out of the app's own `public/`.
  publicDir: FRAMES,
  onProgress: () => {},
});

await mkdir(OUT, { recursive: true });
const report = [];

for (const id of scenes) {
  const composition = await selectComposition({ serveUrl, id, inputProps: {} });
  const base = path.join(OUT, id);

  // Poster: the frame `POSTER_AT` names, clamped into the composition. A still
  // is what the <video> shows before it is allowed to play and what a
  // reduced-motion or data-saver visitor sees INSTEAD of the clip — so it is
  // the clip's landed end state, not its first frame. clips.mjs argues it.
  const posterFrame = Math.min(
    composition.durationInFrames - 1,
    Math.max(0, Math.round((POSTER_AT[id] ?? 0) * composition.fps)),
  );
  await renderStill({
    composition,
    serveUrl,
    output: `${base}.jpg`,
    frame: posterFrame,
    imageFormat: "jpeg",
    jpegQuality: 82,
    inputProps: {},
  });

  const encodes = {};
  for (const [ext, opts] of [
    // VP9/WebM: the modern half. CRF is the quality knob; 34 is visually clean
    // on flat UI at this size, where a photographic source would band.
    ["webm", { codec: "vp9", crf: 34 }],
    // H.264/MP4: the fallback every browser and every embedded player takes.
    ["mp4", { codec: "h264", crf: 26 }],
  ]) {
    const outputLocation = `${base}.${ext}`;
    await renderMedia({
      composition,
      serveUrl,
      // `outputLocation`, NOT `output`: renderMedia ignores `output` without a
      // word and writes the encode to a temp file that is then thrown away, so
      // the only symptom is a missing clip at the end of a successful-looking
      // render. renderStill is the one that takes `output`.
      outputLocation,
      // NO AUDIO TRACK — and this line is what makes that true. The comment
      // that used to sit here said the clips were "silent by construction"
      // and it was WRONG: every shipped file carried a real track (Opus in
      // the webm, AAC in the mp4, ~317 kbit/s declared), because Remotion's
      // `getShouldRenderAudio` answers "maybe" when it cannot see the asset
      // list yet and "maybe" muxes a track. Silent is not absent — an absent
      // track is bytes not spent and a decoder not set up, on clips the page
      // plays `muted` and no visitor can ever hear.
      muted: true,
      inputProps: {},
      ...opts,
    });
    encodes[ext] = (await stat(outputLocation)).size;
  }

  const poster = (await stat(`${base}.jpg`)).size;
  report.push({
    id,
    width: composition.width,
    height: composition.height,
    seconds: +(composition.durationInFrames / composition.fps).toFixed(2),
    webm: encodes.webm,
    mp4: encodes.mp4,
    poster,
  });
  console.log(
    `  ${id}: ${composition.width}x${composition.height} · ${(composition.durationInFrames / composition.fps).toFixed(2)}s · ` +
      `webm ${kb(encodes.webm)} · mp4 ${kb(encodes.mp4)} · poster ${kb(poster)} @ f${posterFrame}`,
  );
}

// The manifest is MERGED, not replaced. A run that skips the hand-captured clip
// (no source .mov) or is narrowed with FOOTAGE_ONLY still rebuilds only some of
// the files on disk — rewriting the manifest from just this run's output would
// quietly delete the entries for clips that are still sitting right there, and
// the manifest is what a reader trusts for byte counts.
const manifestPath = path.join(OUT, "manifest.json");
const previous = await readFile(manifestPath, "utf8").then((t) => JSON.parse(t).clips ?? [], () => []);
const byId = new Map(previous.map((c) => [c.id, c]));
for (const c of report) byId.set(c.id, c);
// Ordered by the clip list, and entries whose files are gone are dropped.
const merged = [];
for (const id of CLIPS) {
  const entry = byId.get(id);
  if (!entry) continue;
  if (await access(path.join(OUT, `${id}.webm`)).then(() => true, () => false)) merged.push(entry);
}
await writeFile(manifestPath, JSON.stringify({ generated: new Date().toISOString(), clips: merged }, null, 2) + "\n");

const over = merged.filter((r) => Math.min(r.webm, r.mp4) > 500 * 1024);
if (over.length) {
  console.error(`\nOver the 500 KB budget: ${over.map((r) => r.id).join(", ")}`);
  process.exit(1);
}
console.log(`\nclips -> ${OUT}`);
