"use client";

import { useState } from "react";

import { Button } from "@/components/ui/button";
import { publicEnv } from "@/lib/env";
import { createClient } from "@/lib/supabase/client";

/**
 * "Continue with Google" — Supabase Auth (Google OAuth provider) sign-in.
 *
 * ## Why this isn't a one-liner `signInWithOAuth` call
 *
 * `supabase.auth.signInWithOAuth({ provider: 'google' })` performs **no**
 * network round-trip: it builds the `/auth/v1/authorize` URL client-side and
 * (unless `skipBrowserRedirect` is set) immediately `window.location.assign`s
 * to it — so its returned `error` is always `null`. When the Google provider
 * is **not enabled** on the Supabase project, that endpoint answers `400` with
 * a raw JSON body `{"msg":"Unsupported provider: provider is not enabled"}`
 * and does **not** redirect. Letting the browser navigate there would dump
 * that JSON on the user — a broken-looking dead end.
 *
 * So we ask for the URL **without** redirecting (`skipBrowserRedirect: true`,
 * which also appends `skip_http_redirect=true`, making `/authorize` reply with
 * JSON instead of a 302), pre-flight it with a `fetch`, and only hand the
 * browser off to Google once we've confirmed the provider is live:
 *
 *   - `4xx`            → provider disabled → inline "not configured" message.
 *   - `200 { url }`    → provider live     → `window.location.assign(url)`.
 *   - network failure  → inline "couldn't reach" message.
 *
 * The PKCE `code_verifier` generated by `signInWithOAuth` is persisted by
 * `@supabase/ssr`'s browser client to a **cookie** (not `localStorage`), so
 * the server-side `/callback` route handler can read it to complete
 * `exchangeCodeForSession`. `skipBrowserRedirect` does not change that — the
 * verifier is written when the URL is built — so the deferred navigation here
 * is fully compatible with the existing SSR callback.
 */

const NOT_CONFIGURED_MESSAGE = "Google sign-in isn't configured yet.";
const UNREACHABLE_MESSAGE =
  "Couldn't reach Google sign-in. Check your connection and try again.";

function GoogleGlyph() {
  return (
    <svg
      width="16"
      height="16"
      viewBox="0 0 48 48"
      aria-hidden="true"
      focusable="false"
    >
      <path
        fill="#EA4335"
        d="M24 9.5c3.54 0 6.71 1.22 9.21 3.6l6.85-6.85C35.9 2.38 30.47 0 24 0 14.62 0 6.51 5.38 2.56 13.22l7.98 6.19C12.43 13.72 17.74 9.5 24 9.5z"
      />
      <path
        fill="#4285F4"
        d="M46.98 24.55c0-1.57-.15-3.09-.38-4.55H24v9.02h12.94c-.58 2.96-2.26 5.48-4.78 7.18l7.73 6c4.51-4.18 7.09-10.36 7.09-17.65z"
      />
      <path
        fill="#FBBC05"
        d="M10.53 28.59c-.48-1.45-.76-2.99-.76-4.59s.27-3.14.76-4.59l-7.98-6.19C.92 16.46 0 20.12 0 24c0 3.88.92 7.54 2.56 10.78l7.97-6.19z"
      />
      <path
        fill="#34A853"
        d="M24 48c6.48 0 11.93-2.13 15.89-5.81l-7.73-6c-2.15 1.45-4.92 2.3-8.16 2.3-6.26 0-11.57-4.22-13.47-9.91l-7.98 6.19C6.51 42.62 14.62 48 24 48z"
      />
    </svg>
  );
}

/**
 * A hairline "or" divider matching the monochrome system's mono label voice.
 * Purely decorative, so it is hidden from assistive tech.
 */
export function AuthOrDivider() {
  return (
    <div className="flex items-center gap-3" aria-hidden="true">
      <span className="h-px flex-1 bg-line" />
      <span className="label-mono">or</span>
      <span className="h-px flex-1 bg-line" />
    </div>
  );
}

export function GoogleSignInButton({
  redirectTo = "/dashboard",
  label = "Continue with Google",
}: {
  /** Same-origin path to land on after the code-exchange. */
  redirectTo?: string;
  label?: string;
}) {
  const [isRedirecting, setIsRedirecting] = useState(false);
  const [error, setError] = useState<string | null>(null);

  async function handleClick() {
    setError(null);
    setIsRedirecting(true);

    // Refuse open redirects: only ever return to a same-origin path.
    const safeRedirect = redirectTo.startsWith("/") ? redirectTo : "/dashboard";
    const callbackUrl = new URL("/callback", window.location.origin);
    callbackUrl.searchParams.set("redirect", safeRedirect);

    const supabase = createClient();
    const { data, error: oauthError } = await supabase.auth.signInWithOAuth({
      provider: "google",
      options: {
        redirectTo: callbackUrl.toString(),
        // Get the URL back instead of navigating — see the file header.
        skipBrowserRedirect: true,
      },
    });

    if (oauthError || !data?.url) {
      setError(NOT_CONFIGURED_MESSAGE);
      setIsRedirecting(false);
      return;
    }

    let response: Response;
    try {
      response = await fetch(data.url, {
        headers: { apikey: publicEnv.NEXT_PUBLIC_SUPABASE_ANON_KEY },
      });
    } catch {
      setError(UNREACHABLE_MESSAGE);
      setIsRedirecting(false);
      return;
    }

    if (!response.ok) {
      // 400 "Unsupported provider: provider is not enabled" lands here.
      setError(NOT_CONFIGURED_MESSAGE);
      setIsRedirecting(false);
      return;
    }

    const payload = (await response.json().catch(() => null)) as {
      url?: string;
    } | null;

    if (!payload?.url) {
      setError(NOT_CONFIGURED_MESSAGE);
      setIsRedirecting(false);
      return;
    }

    // Provider is live — hand the browser to Google's consent screen. Keep the
    // button disabled through the navigation.
    window.location.assign(payload.url);
  }

  return (
    <div className="space-y-2">
      <Button
        type="button"
        variant="outline"
        className="w-full"
        onClick={handleClick}
        disabled={isRedirecting}
      >
        <GoogleGlyph />
        {isRedirecting ? "Connecting…" : label}
      </Button>

      {error ? (
        <p
          role="alert"
          className="rounded-md border border-reject/40 bg-reject/10 px-3 py-2 text-sm text-reject"
        >
          {error}
        </p>
      ) : null}
    </div>
  );
}
